# Generated by Django 4.1.3 on 2023-05-21 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_refer',
            fields=[
                ('Address', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('Bed', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')])),
                ('Bath', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four')])),
                ('Storage', models.BooleanField(default=False)),
                ('Wifi', models.BooleanField(default=False)),
                ('Referal_code', models.CharField(max_length=7, verbose_name="enter your friend's referal code if available")),
            ],
        ),
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('link', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('counter', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
