# Generated by Django 4.1.3 on 2023-05-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refer',
            name='Reffered_by',
            field=models.CharField(default='l', max_length=100),
            preserve_default=False,
        ),
    ]
